nome = input("digite seu nome: ")
idade = input("digite sua idade: ")
seuSexo = input("digite seu sexo: ")
seuEndereco = input("digite seu endereço: ")
seuTelefone = input("digite o número do seu celular: ")
print("Seu nome é: ",nome)
print("Sua idade é: ",idade)
print("Seu sexo é: ",seuSexo)
print("Seu endereço: ",seuEndereco)
print("Seu telefone é: ",seuTelefone)
